Repository SINTEF/pyopia, pull requests merged in 2023-01, with the labels that each got.

#51 specify numpy version
  environment.yml
  notebooks/pipeline.ipynb
  pyopia/__init__.py
Labels: bug

#54 53 make function for default steps for silcam
  notebooks/pipeline.ipynb
  pyopia/__init__.py
  pyopia/instrument/silcam.py
  pyopia/pipeline.py
Labels: enhancement

#61 Data dict docs
  README.md
  docs/source/conf.py
  notebooks/pipeline.ipynb
  pyopia/__init__.py
  pyopia/instrument/silcam.py
  pyopia/pipeline.py
  pyopia/process.py
Labels: documentation, enhancement

#64 56 implement moving background in pipeline
  notebooks/pipeline.ipynb
  pyopia/__init__.py
  pyopia/background.py
  pyopia/pipeline.py
Labels: enhancement

#66 Holo background test
  notebooks/pipeline-holo.ipynb
  pyopia/__init__.py
  pyopia/background.py
  pyopia/instrument/holo.py
Labels: enhancement
