Repository SINTEF/pyopia, pull requests merged in 2024-09, with the labels that each got.

#214 Version 2.0.0
  .github/workflows/build-and-test.yml
  .gitignore
  .readthedocs.yaml
  README.md
  docs/_toc.yml
  docs/api.rst
  docs/examples.md
  docs/notebooks/STATSnc.ipynb
  docs/notebooks/background_correction.ipynb
  docs/notebooks/cli.ipynb
  docs/notebooks/config.toml
  docs/notebooks/exploring_pipeline_data.ipynb
  docs/notebooks/montaging.ipynb
  docs/notebooks/pipeline_step_by_step.ipynb
  docs/notebooks/stats.ipynb
  docs/notebooks/toml_config.ipynb
  environment.yml
  notebooks/config-holo.toml
  notebooks/config.toml
  notebooks/pipeline-holo.ipynb
  notebooks/single-image-stats-holo.ipynb
  notebooks/single-image-stats.ipynb
  pyopia/__init__.py
  pyopia/background.py
  pyopia/classify.py
  pyopia/cli.py
  pyopia/exampledata.py
  pyopia/instrument/common.py
  pyopia/instrument/holo.py
  pyopia/instrument/silcam.py
  pyopia/io.py
  pyopia/pipeline.py
  pyopia/plotting.py
  pyopia/process.py
  pyopia/statistics.py
  pyopia/tests/test_classify.py
  pyopia/tests/test_notebooks.py
  pyopia/tests/test_pipeline.py
  pyproject.toml
Labels: enhancement

#239 update scikit image
  pyopia/__init__.py
  pyproject.toml
Labels: bug

#265 241 files to process class
  pyopia/__init__.py
  pyopia/cli.py
  pyopia/pipeline.py
  pyopia/process.py
Labels: new-feature

#283 Fix bug in pyopia merge-mfdata
  pyopia/__init__.py
  pyopia/io.py
Labels: bug

#286 Image conversion: Bayer RG8 to RGB
  pyopia/__init__.py
  pyopia/instrument/silcam.py
Labels: new-feature

#260 Enhancements for holo processing post 2.0
  notebooks/pipeline-holo.ipynb
  pyopia/__init__.py
  pyopia/instrument/holo.py
Labels: enhancement

#285 update docs
  docs/_toc.yml
  docs/notebooks/STATSnc.ipynb
  docs/notebooks/big_datasets.ipynb
  docs/notebooks/cli.ipynb
  docs/notebooks/toml_config.ipynb
  pyopia/__init__.py
  pyopia/instrument/holo.py
  pyopia/instrument/silcam.py
  pyopia/instrument/uvp.py
  pyopia/io.py
  pyopia/tests/test_pipeline.py
Labels: documentation

#278 Use open_mfdataset to load image_stats instead of just loading the last image
  pyopia/__init__.py
  pyopia/io.py
  pyopia/statistics.py
Labels: bug

#271 270 add option for silcam simulator to simulate different particles rather than just black spheres
  .gitignore
  pyopia/__init__.py
  pyopia/simulator/silcam.py
Labels: patch / enhancement

#293 clearer merge_and_save_mfdataset docstring
  pyopia/__init__.py
  pyopia/io.py
Labels: documentation

#295 Better documentation of acceptable SilCam filenames
  pyopia/__init__.py
  pyopia/instrument/silcam.py
Labels: documentation

#305 Change the cli.py
  pyopia/__init__.py
  pyopia/cli.py
Labels: bug

#319 318 dictionary lookups in classifypreprocessing may slow down processing
  pyopia/__init__.py
  pyopia/classify.py
Labels: bug, patch / enhancement
