Repository SINTEF/pyopia, pull requests merged in 2024-08, with the labels that each got.

#167 163 Guide for running steps manually
  .github/workflows/build-and-test.yml
  docs/_toc.yml
  docs/notebooks/exploring_pipeline_data.ipynb
  docs/notebooks/pipeline_step_by_step.ipynb
  pyopia/__init__.py
  pyopia/pipeline.py
Labels: documentation

#162 make reconstruction kernel inclusive of upper limit z plane
  pyopia/__init__.py
  pyopia/instrument/holo.py
Labels: bug, enhancement

#168 Classifier debugging
  README.md
  docs/intro.md
  pyopia/__init__.py
  pyopia/background.py
  pyopia/instrument/silcam.py
  pyopia/process.py
  pyopia/statistics.py
Labels: bug, documentation, enhancement, dependencies

#171 move exampledata.py to pyopia module level
  README.md
  docs/notebooks/STATSnc.ipynb
  docs/notebooks/exploring_pipeline_data.ipynb
  docs/notebooks/pipeline_step_by_step.ipynb
  docs/notebooks/stats.ipynb
  notebooks/pipeline-holo.ipynb
  notebooks/single-image-stats-holo.ipynb
  notebooks/single-image-stats.ipynb
  pyopia/__init__.py
  pyopia/exampledata.py
  pyopia/tests/test_pipeline.py
  pyopia/tests/testdata.py
Labels: enhancement

#174 91 the name imc is used for different things with different datatypes
  docs/notebooks/exploring_pipeline_data.ipynb
  docs/notebooks/stats.ipynb
  notebooks/config-holo.toml
  notebooks/config.toml
  notebooks/pipeline-holo.ipynb
  notebooks/single-image-stats-holo.ipynb
  notebooks/single-image-stats.ipynb
  pyopia/background.py
  pyopia/classify.py
  pyopia/instrument/holo.py
  pyopia/instrument/silcam.py
  pyopia/pipeline.py
  pyopia/plotting.py
  pyopia/process.py
  pyopia/statistics.py
  pyopia/tests/test_pipeline.py
Labels: bug, enhancement

#181 proposed description of version numbering
  README.md
Labels: documentation

#185 182 test for classification
  .gitignore
  pyopia/__init__.py
  pyopia/exampledata.py
  pyopia/tests/test_classify.py
Labels: testing

#177 91 the name imc is used for different things with different datatypes
  .gitignore
  notebooks/config.toml
  pyopia/__init__.py
  pyopia/background.py
  pyopia/instrument/silcam.py
  pyopia/pipeline.py
  pyopia/plotting.py
  pyopia/process.py
  pyopia/tests/test_pipeline.py
Labels: bug, enhancement

#190 189 xarray formatting of netcdf data causes error if first images have no particles
  pyopia/__init__.py
  pyopia/io.py
  pyopia/process.py
Labels: bug

#188 updates of jupyterbook docs
  docs/_toc.yml
  docs/examples.md
  docs/notebooks/config.toml
  docs/notebooks/exploring_pipeline_data.ipynb
  docs/notebooks/montaging.ipynb
  docs/notebooks/toml_config.ipynb
  pyopia/__init__.py
Labels: documentation

#194 186 pyopiacli not working for raw files updates
  docs/notebooks/cli.ipynb
  pyopia/__init__.py
Labels: documentation

#195 192 Pass minimum_area to segmentation function
  pyopia/__init__.py
  pyopia/process.py
Labels: bug

#197 196 Add optional config option for CreateBackground image source
  pyopia/__init__.py
  pyopia/background.py
Labels: enhancement

#193 implement option to not append STATS.nc files
  docs/notebooks/config.toml
  pyopia/__init__.py
  pyopia/io.py
  pyproject.toml
Labels: bug, enhancement

#206 198 pyopiastatisticsmake timeseries vd makes dataframe with times upside down oldest first newest last
  pyopia/__init__.py
  pyopia/statistics.py
Labels: bug

#208 90 switch from using print statements to using a logger
  docs/notebooks/toml_config.ipynb
  pyopia/cli.py
  pyopia/pipeline.py
  pyopia/process.py
Labels: enhancement

#203 add nbconvert jobs to github build-and-test workflow
  .github/workflows/build-and-test.yml
  pyopia/tests/test_notebooks.py
  pyproject.toml
Labels: testing

#211 check for uint8 images in ROI files and scale appropriately
  pyopia/__init__.py
  pyopia/statistics.py
Labels: bug

#205 Tensorflow updates
  .github/workflows/build-and-test.yml
  .gitignore
  .readthedocs.yaml
  environment.yml
  notebooks/config.toml
  notebooks/pipeline-holo.ipynb
  notebooks/single-image-stats-holo.ipynb
  notebooks/single-image-stats.ipynb
  pyopia/classify.py
  pyopia/cli.py
  pyopia/exampledata.py
  pyopia/io.py
  pyopia/process.py
  pyopia/statistics.py
  pyopia/tests/test_classify.py
  pyproject.toml
Labels: enhancement, dependencies
